services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - default
      - dokploy-network
    labels:
      - traefik.docker.network=dokploy-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ChatIRL;User Id=sa;Password=Receba123!;TrustServerCertificate=True
    depends_on:
      - db
    restart: on-failure

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Receba123!
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
